// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CagedApi.Migrations
{
    [DbContext(typeof(ProgressionDb))]
    [Migration("20240711200809_UserClass")]
    partial class UserClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CagedApi.Models.Chord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarreIndicator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("MutedFrets")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgressionId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("Shape")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("ProgressionId");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("CagedApi.Models.Progression", b =>
                {
                    b.Property<int>("ProgressionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgressionId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProgressionId");

                    b.HasIndex("UserId");

                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("CagedApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CagedApi.Models.Chord", b =>
                {
                    b.HasOne("CagedApi.Models.Progression", null)
                        .WithMany("ChordList")
                        .HasForeignKey("ProgressionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CagedApi.Models.Progression", b =>
                {
                    b.HasOne("CagedApi.Models.User", null)
                        .WithMany("ProgressionList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CagedApi.Models.Progression", b =>
                {
                    b.Navigation("ChordList");
                });

            modelBuilder.Entity("CagedApi.Models.User", b =>
                {
                    b.Navigation("ProgressionList");
                });
#pragma warning restore 612, 618
        }
    }
}
